#resilience4j.ratelimiter:
#  instances:
#    consumerservice:
#      limitForPeriod: 2
#      limitRefreshPeriod: 4s
#      timeoutDuration: 0
#      registerHealthIndicator: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#  